"""Bounded, non-executing analyzers for local vulnerability evidence."""

from .patch_analyzer import (
    DEFAULT_MAX_CANDIDATES,
    DEFAULT_MAX_FILES,
    DEFAULT_MAX_HUNK_LINES,
    DEFAULT_MAX_HUNKS,
    DEFAULT_MAX_PATCH_CHARS,
    DEFAULT_MAX_PATCH_LINES,
    ChangedFile,
    PatchAnalysis,
    PatchAnalysisError,
    PatchCandidate,
    PatchConflict,
    PatchFormatError,
    PatchHunk,
    PatchLimitExceeded,
    PatchLine,
    PatchUncertainty,
    UnsafePatchPath,
    analyze_patch,
    compare_patch_sources,
)

__all__ = [
    "DEFAULT_MAX_CANDIDATES",
    "DEFAULT_MAX_FILES",
    "DEFAULT_MAX_HUNK_LINES",
    "DEFAULT_MAX_HUNKS",
    "DEFAULT_MAX_PATCH_CHARS",
    "DEFAULT_MAX_PATCH_LINES",
    "ChangedFile",
    "PatchAnalysis",
    "PatchAnalysisError",
    "PatchCandidate",
    "PatchConflict",
    "PatchFormatError",
    "PatchHunk",
    "PatchLimitExceeded",
    "PatchLine",
    "PatchUncertainty",
    "UnsafePatchPath",
    "analyze_patch",
    "compare_patch_sources",
]
